### ISSUE TITLE
Unable to use libmadam with toast

### ISSUE THREAD

**Issue by ziotom78** [hpc4cmb/libmadam#1]
When using toast with the `--madam` flag, libmadam crashes with the following error message, caused by a missing function `zhhev` (part of LAPACK):

```
$ ./toast_satellite_sim.py --madam
Traceback (most recent call last):
  File "/home/tomasi/work/CORE/toast-master/venv/lib/python3.4/site-packages/toast-2.0-py3.4-linux-x86_64.egg/toast/map/madam.py", line 27, in <module>
    libmadam = ct.CDLL('libmadam.so')
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/tomasi/work/CORE/toast-master/venv/lib/libmadam.so: undefined symbol: zheev_

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./toast_satellite_sim.py", line 4, in <module>
    __import__('pkg_resources').run_script('toast==2.0', 'toast_satellite_sim.py')
  File "/home/tomasi/work/CORE/toast-master/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/tomasi/work/CORE/toast-master/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/tomasi/work/CORE/toast-master/venv/lib/python3.4/site-packages/toast-2.0-py3.4-linux-x86_64.egg/EGG-INFO/scripts/toast_satellite_sim.py", line 20, in <module>
    import toast.map as tm
  File "/home/tomasi/work/CORE/toast-master/venv/lib/python3.4/site-packages/toast-2.0-py3.4-linux-x86_64.egg/toast/map/__init__.py", line 8, in <module>
    from .madam import OpMadam
  File "/home/tomasi/work/CORE/toast-master/venv/lib/python3.4/site-packages/toast-2.0-py3.4-linux-x86_64.egg/toast/map/madam.py", line 31, in <module>
    libmadam = ct.CDLL(path)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/tomasi/work/CORE/toast-master/venv/lib/libmadam.so.0: undefined symbol: zheev_
```

Running `ldd` on libmadam.so produces the following output:

```
$ ldd src/.libs/libmadam.so                                                                                                    [2:28:02]
    linux-vdso.so.1 =>  (0x00007ffdbc32f000)
    libcfitsio.so.3 => /usr/lib/x86_64-linux-gnu/libcfitsio.so.3 (0x00007f171ab00000)
    libfftw3.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3.so.3 (0x00007f171a708000)
    libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f171a3ed000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f171a0e7000)
    libmpi_f90.so.1 => /usr/lib/libmpi_f90.so.1 (0x00007f1719ee2000)
    libmpi_f77.so.1 => /usr/lib/libmpi_f77.so.1 (0x00007f1719cad000)
    libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f1719a9e000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1719888000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f17194c2000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f17192a4000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f171908b000)
    libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f1718e4e000)
    libmpi.so.1 => /usr/lib/libmpi.so.1 (0x00007f1718acd000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f172508e000)
    libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f17188c9000)
    libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007f1718689000)
    libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f171847f000)
    libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f1718273000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f171806f000)
```

My Linux version is Mint 17.2, with gfortran 4.8.4 and LAPACK 3.5.0. LAPACK has been installed using `apt-get`, so the library is in a standard directory (`/usr/lib/liblapack.so`).

**Comment by ziotom78** [comment]
Ok, I think I solved this issue. The point is to force `make` to include LAPACK by listing it manually when invoking `make`:

```
make LIBS=-llapack
```

(you might want to add `LDFLAGS=-L<path to LAPACK>`, if you have it installed in some non-standard location). Using this trick, `ldd libmadam.so` correctly lists `liblapack.so` and solves the problem.

I am keeping this issue open, since I think it would be more user-frendly if the code already took care of this.

**Comment by tskisner** [comment]
Thanks Maurizio, indeed the configure check for lapack should add that library internally to AM_LIBS.  Another person just reported a problem with OpenMP linking, so we'll try to make a debugging pass on the build system soon.

**Comment by keskitalo** [comment]
The commits from today include a number of improvements to the build system, including the missing BLAS/LAPACK library macros. There are also Python and C test cases that run with "make check".

Maurizio, if you could try again and let us know if things now work in your end. I can then close the issue.

**Comment by ziotom78** [comment]
Thanks a lot, Reijo, now LAPACK is included automatically and no more `LIBS` magic is needed.

However, I am experiencing a few more problems during the build process and during `make check`. To keep things clear, I am going to close this issue and open new ones.
